//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDPAnalyser.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDPAnalyser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method ähnelt.
        /// </summary>
        public static string Analysis_methodCaption {
            get {
                return ResourceManager.GetString("Analysis_methodCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictionary Search ähnelt.
        /// </summary>
        public static string Analysis_methodList1 {
            get {
                return ResourceManager.GetString("Analysis_methodList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hill Climbing ähnelt.
        /// </summary>
        public static string Analysis_methodList2 {
            get {
                return ResourceManager.GetString("Analysis_methodList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Analysis Method ähnelt.
        /// </summary>
        public static string Analysis_methodTooltip {
            get {
                return ResourceManager.GetString("Analysis_methodTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy all lines ähnelt.
        /// </summary>
        public static string Copy_all {
            get {
                return ResourceManager.GetString("Copy_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy key ähnelt.
        /// </summary>
        public static string Copy_key {
            get {
                return ResourceManager.GetString("Copy_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy key phrase ähnelt.
        /// </summary>
        public static string Copy_keyphrase {
            get {
                return ResourceManager.GetString("Copy_keyphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy selected line ähnelt.
        /// </summary>
        public static string Copy_line {
            get {
                return ResourceManager.GetString("Copy_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy text ähnelt.
        /// </summary>
        public static string Copy_text {
            get {
                return ResourceManager.GetString("Copy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy value ähnelt.
        /// </summary>
        public static string Copy_value {
            get {
                return ResourceManager.GetString("Copy_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elapsed: ähnelt.
        /// </summary>
        public static string ElapsedLabel {
            get {
                return ResourceManager.GetString("ElapsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End: ähnelt.
        /// </summary>
        public static string EndLabel {
            get {
                return ResourceManager.GetString("EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input ähnelt.
        /// </summary>
        public static string InputCaption {
            get {
                return ResourceManager.GetString("InputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input data for analysis ähnelt.
        /// </summary>
        public static string InputTooltip {
            get {
                return ResourceManager.GetString("InputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iterations ähnelt.
        /// </summary>
        public static string IterationsCaption {
            get {
                return ResourceManager.GetString("IterationsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the number of iterations of the algorithm. ähnelt.
        /// </summary>
        public static string IterationsTooltip {
            get {
                return ResourceManager.GetString("IterationsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 1 Maximum ähnelt.
        /// </summary>
        public static string Key1MaxCaption {
            get {
                return ResourceManager.GetString("Key1MaxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the maximum size of key 1. ähnelt.
        /// </summary>
        public static string Key1MaxTooltip {
            get {
                return ResourceManager.GetString("Key1MaxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 1 Minimum ähnelt.
        /// </summary>
        public static string Key1MinCaption {
            get {
                return ResourceManager.GetString("Key1MinCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the minimum size of key 1. ähnelt.
        /// </summary>
        public static string Key1MinTooltip {
            get {
                return ResourceManager.GetString("Key1MinTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 1 ähnelt.
        /// </summary>
        public static string Key1SizeCaption {
            get {
                return ResourceManager.GetString("Key1SizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the size of key 1. ähnelt.
        /// </summary>
        public static string Key1SizeTooltip {
            get {
                return ResourceManager.GetString("Key1SizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 2 Maximum ähnelt.
        /// </summary>
        public static string Key2MaxCaption {
            get {
                return ResourceManager.GetString("Key2MaxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the maximum size of key 2. ähnelt.
        /// </summary>
        public static string Key2MaxTooltip {
            get {
                return ResourceManager.GetString("Key2MaxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 2 Minimum ähnelt.
        /// </summary>
        public static string Key2MinCaption {
            get {
                return ResourceManager.GetString("Key2MinCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the minimum size of key 2. ähnelt.
        /// </summary>
        public static string Key2MinTooltip {
            get {
                return ResourceManager.GetString("Key2MinTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key 2 ähnelt.
        /// </summary>
        public static string Key2SizeCaption {
            get {
                return ResourceManager.GetString("Key2SizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the size of key 2. ähnelt.
        /// </summary>
        public static string Key2SizeTooltip {
            get {
                return ResourceManager.GetString("Key2SizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Sizes ähnelt.
        /// </summary>
        public static string KeyGroup {
            get {
                return ResourceManager.GetString("KeyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        public static string KeyHeader {
            get {
                return ResourceManager.GetString("KeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Phrase ähnelt.
        /// </summary>
        public static string KeyPhraseHeader {
            get {
                return ResourceManager.GetString("KeyPhraseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keys / sec: ähnelt.
        /// </summary>
        public static string Keys_secLabel {
            get {
                return ResourceManager.GetString("Keys_secLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keysize ähnelt.
        /// </summary>
        public static string KeySizeCaption {
            get {
                return ResourceManager.GetString("KeySizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the keysize to be searched. ähnelt.
        /// </summary>
        public static string KeySizeTooltip {
            get {
                return ResourceManager.GetString("KeySizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywords ähnelt.
        /// </summary>
        public static string KeywordsCaption {
            get {
                return ResourceManager.GetString("KeywordsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a list of keywords. ähnelt.
        /// </summary>
        public static string KeywordsTooltip {
            get {
                return ResourceManager.GetString("KeywordsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string LanguageCaption {
            get {
                return ResourceManager.GetString("LanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die english ähnelt.
        /// </summary>
        public static string LanguageList1 {
            get {
                return ResourceManager.GetString("LanguageList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die german ähnelt.
        /// </summary>
        public static string LanguageList2 {
            get {
                return ResourceManager.GetString("LanguageList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die french ähnelt.
        /// </summary>
        public static string LanguageList3 {
            get {
                return ResourceManager.GetString("LanguageList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die italian ähnelt.
        /// </summary>
        public static string LanguageList4 {
            get {
                return ResourceManager.GetString("LanguageList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the language of the ciphertext. ähnelt.
        /// </summary>
        public static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local ähnelt.
        /// </summary>
        public static string LocalLabel {
            get {
                return ResourceManager.GetString("LocalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transposition Bruteforce length ähnelt.
        /// </summary>
        public static string MaxLengthCaption {
            get {
                return ResourceManager.GetString("MaxLengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the max length to be bruteforced (max: 20). ähnelt.
        /// </summary>
        public static string MaxLengthTooltip {
            get {
                return ResourceManager.GetString("MaxLengthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string OutputCaption {
            get {
                return ResourceManager.GetString("OutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string OutputTooltip {
            get {
                return ResourceManager.GetString("OutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IDP Analyzer ähnelt.
        /// </summary>
        public static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performs an attack on the double columnar transposition ähnelt.
        /// </summary>
        public static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining: ähnelt.
        /// </summary>
        public static string RemainingLabel {
            get {
                return ResourceManager.GetString("RemainingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repetitions ähnelt.
        /// </summary>
        public static string RepeatingsCaption {
            get {
                return ResourceManager.GetString("RepeatingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the number of repetitions of the algorithm. ähnelt.
        /// </summary>
        public static string RepeatingsTooltip {
            get {
                return ResourceManager.GetString("RepeatingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start: ähnelt.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string TextHeader {
            get {
                return ResourceManager.GetString("TextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top Ten ähnelt.
        /// </summary>
        public static string TopTenLabel {
            get {
                return ResourceManager.GetString("TopTenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string ValueHeader {
            get {
                return ResourceManager.GetString("ValueHeader", resourceCulture);
            }
        }
    }
}
