//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuadraticSieve.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuadraticSieve.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Peers: ähnelt.
        /// </summary>
        internal static string Active_Peers_ {
            get {
                return ResourceManager.GetString("Active_Peers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bit ähnelt.
        /// </summary>
        internal static string Bit {
            get {
                return ResourceManager.GetString("Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bits ähnelt.
        /// </summary>
        internal static string Bits {
            get {
                return ResourceManager.GetString("Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel ähnelt.
        /// </summary>
        internal static string ChannelCaption {
            get {
                return ResourceManager.GetString("ChannelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel of the Peer2Peer network ähnelt.
        /// </summary>
        internal static string ChannelTooltip {
            get {
                return ResourceManager.GetString("ChannelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Composite Factor ähnelt.
        /// </summary>
        internal static string Composite_Factor {
            get {
                return ResourceManager.GetString("Composite_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cores used: ähnelt.
        /// </summary>
        internal static string Cores_used_ {
            get {
                return ResourceManager.GetString("Cores_used_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CoresUsed ähnelt.
        /// </summary>
        internal static string CoresUsedCaption {
            get {
                return ResourceManager.GetString("CoresUsedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose how many cores should be used for sieving ähnelt.
        /// </summary>
        internal static string CoresUsedTooltip {
            get {
                return ResourceManager.GetString("CoresUsedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day ähnelt.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete cache ähnelt.
        /// </summary>
        internal static string DeleteCacheCaption {
            get {
                return ResourceManager.GetString("DeleteCacheCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If checked, this plugin will delete the old cache file before it starts sieving ähnelt.
        /// </summary>
        internal static string DeleteCacheTooltip {
            get {
                return ResourceManager.GetString("DeleteCacheTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die digit ähnelt.
        /// </summary>
        internal static string Digit {
            get {
                return ResourceManager.GetString("Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die digits ähnelt.
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloaded: ähnelt.
        /// </summary>
        internal static string Downloaded_ {
            get {
                return ResourceManager.GetString("Downloaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elapsed: ähnelt.
        /// </summary>
        internal static string Elapsed_ {
            get {
                return ResourceManager.GetString("Elapsed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End: ähnelt.
        /// </summary>
        internal static string End_ {
            get {
                return ResourceManager.GetString("End_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factorlist ähnelt.
        /// </summary>
        internal static string Factorlist {
            get {
                return ResourceManager.GetString("Factorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found enough relations. Please wait... ähnelt.
        /// </summary>
        internal static string Found_enough_relations {
            get {
                return ResourceManager.GetString("Found_enough_relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found Relations: ähnelt.
        /// </summary>
        internal static string Found_Relations_ {
            get {
                return ResourceManager.GetString("Found_Relations_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour ähnelt.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input too big (Upper limit: 10^274; given input: 10^{0}) ähnelt.
        /// </summary>
        internal static string Input_too_big_ {
            get {
                return ResourceManager.GetString("Input_too_big_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a number &gt;= 2 ähnelt.
        /// </summary>
        internal static string Input_too_small_ {
            get {
                return ResourceManager.GetString("Input_too_small_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number input ähnelt.
        /// </summary>
        internal static string InputNumberCaption {
            get {
                return ResourceManager.GetString("InputNumberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the number you want to factorize ähnelt.
        /// </summary>
        internal static string InputNumberTooltip {
            get {
                return ResourceManager.GetString("InputNumberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local Sieving (Not Connected) ähnelt.
        /// </summary>
        internal static string Local_Sieving_ {
            get {
                return ResourceManager.GetString("Local_Sieving_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute ähnelt.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Needed Relations: ähnelt.
        /// </summary>
        internal static string Needed_Relations_ {
            get {
                return ResourceManager.GetString("Needed_Relations_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string NoneLeft {
            get {
                return ResourceManager.GetString("NoneLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Now sieving first composite factor. ähnelt.
        /// </summary>
        internal static string Now_sieving_first_composite_factor {
            get {
                return ResourceManager.GetString("Now_sieving_first_composite_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other peer finished sieving. ähnelt.
        /// </summary>
        internal static string Other_peer_finished_sieving {
            get {
                return ResourceManager.GetString("Other_peer_finished_sieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factors output ähnelt.
        /// </summary>
        internal static string OutputFactorsCaption {
            get {
                return ResourceManager.GetString("OutputFactorsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your factors will be sent here ähnelt.
        /// </summary>
        internal static string OutputFactorsTooltip {
            get {
                return ResourceManager.GetString("OutputFactorsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peer2Peer ähnelt.
        /// </summary>
        internal static string Peer2Peer {
            get {
                return ResourceManager.GetString("Peer2Peer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quadratic Sieve ähnelt.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modern factorization algorithm ähnelt.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prime Factor ähnelt.
        /// </summary>
        internal static string Prime_Factor {
            get {
                return ResourceManager.GetString("Prime_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress ähnelt.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue: ähnelt.
        /// </summary>
        internal static string Queue_ {
            get {
                return ResourceManager.GetString("Queue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This relation package was sieved by {0} but we loaded it. ähnelt.
        /// </summary>
        internal static string Relpack_loaded {
            get {
                return ResourceManager.GetString("Relpack_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This relation package got lost. ähnelt.
        /// </summary>
        internal static string Relpack_lost {
            get {
                return ResourceManager.GetString("Relpack_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die other user ähnelt.
        /// </summary>
        internal static string Relpack_other {
            get {
                return ResourceManager.GetString("Relpack_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This relation package was sieved by an unknown user and we didn&apos;t load it yet. ähnelt.
        /// </summary>
        internal static string Relpack_unknown {
            get {
                return ResourceManager.GetString("Relpack_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This relation package was sieved by us. ähnelt.
        /// </summary>
        internal static string Relpack_us {
            get {
                return ResourceManager.GetString("Relpack_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining: ähnelt.
        /// </summary>
        internal static string Remaining_ {
            get {
                return ResourceManager.GetString("Remaining_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching trivial factors. ähnelt.
        /// </summary>
        internal static string Searching_trivial_factors {
            get {
                return ResourceManager.GetString("Searching_trivial_factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die second ähnelt.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds left ähnelt.
        /// </summary>
        internal static string seconds_left {
            get {
                return ResourceManager.GetString("seconds_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieving finished. Found all {0} factors. ähnelt.
        /// </summary>
        internal static string Sieving_finished {
            get {
                return ResourceManager.GetString("Sieving_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieving now. ähnelt.
        /// </summary>
        internal static string Sieving_now {
            get {
                return ResourceManager.GetString("Sieving_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sieving finished. ähnelt.
        /// </summary>
        internal static string SievingFinished2 {
            get {
                return ResourceManager.GetString("SievingFinished2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start: ähnelt.
        /// </summary>
        internal static string Start_ {
            get {
                return ResourceManager.GetString("Start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting, please wait. ähnelt.
        /// </summary>
        internal static string Starting_quadratic_sieve {
            get {
                return ResourceManager.GetString("Starting_quadratic_sieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State: ähnelt.
        /// </summary>
        internal static string State_ {
            get {
                return ResourceManager.GetString("State_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy status key ähnelt.
        /// </summary>
        internal static string StatusKeyButtonCaption {
            get {
                return ResourceManager.GetString("StatusKeyButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy status key to clipboard. The key can then be used to upload it together with the job using the P2PEditor. ähnelt.
        /// </summary>
        internal static string StatusKeyButtonTooltip {
            get {
                return ResourceManager.GetString("StatusKeyButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopped by user. ähnelt.
        /// </summary>
        internal static string Stopped_by_user {
            get {
                return ResourceManager.GetString("Stopped_by_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploaded: ähnelt.
        /// </summary>
        internal static string Uploaded_ {
            get {
                return ResourceManager.GetString("Uploaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Peer2Peer ähnelt.
        /// </summary>
        internal static string UsePeer2PeerCaption {
            get {
                return ResourceManager.GetString("UsePeer2PeerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If checked, this plugin will connect to Peer2Peer network to sieve together with other clients ähnelt.
        /// </summary>
        internal static string UsePeer2PeerTooltip {
            get {
                return ResourceManager.GetString("UsePeer2PeerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die very soon ähnelt.
        /// </summary>
        internal static string very_soon {
            get {
                return ResourceManager.GetString("very_soon", resourceCulture);
            }
        }
    }
}
