//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkspaceManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkspaceManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align center ähnelt.
        /// </summary>
        public static string Align_Center {
            get {
                return ResourceManager.GetString("Align_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align justify ähnelt.
        /// </summary>
        public static string Align_Justify {
            get {
                return ResourceManager.GetString("Align_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align left ähnelt.
        /// </summary>
        public static string Align_Left {
            get {
                return ResourceManager.GetString("Align_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align right ähnelt.
        /// </summary>
        public static string Align_Right {
            get {
                return ResourceManager.GetString("Align_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always closed ähnelt.
        /// </summary>
        public static string AlwaysClosedComponentAppearance {
            get {
                return ResourceManager.GetString("AlwaysClosedComponentAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always opened ähnelt.
        /// </summary>
        public static string AlwaysOpenedComponentAppearance {
            get {
                return ResourceManager.GetString("AlwaysOpenedComponentAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysis/Generic: ähnelt.
        /// </summary>
        public static string AnalysisGeneric_Label {
            get {
                return ResourceManager.GetString("AnalysisGeneric_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysis/Specific: ähnelt.
        /// </summary>
        public static string AnalysisSpecific_Label {
            get {
                return ResourceManager.GetString("AnalysisSpecific_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asymmetric: ähnelt.
        /// </summary>
        public static string Asymmetric_Label {
            get {
                return ResourceManager.GetString("Asymmetric_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add image to workspace ähnelt.
        /// </summary>
        public static string BBox_Add_Image_to_Workspace_Tooltip {
            get {
                return ResourceManager.GetString("BBox_Add_Image_to_Workspace_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add memo (for descriptions) to the workspace ähnelt.
        /// </summary>
        public static string BBox_Add_Text_to_Workspace_Tooltip {
            get {
                return ResourceManager.GetString("BBox_Add_Text_to_Workspace_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjust the zoom of the workspace automatically so that all components can be seen to the maximum (Ctrl + F) ähnelt.
        /// </summary>
        public static string BBox_Fit_to_Screen_Tooltip {
            get {
                return ResourceManager.GetString("BBox_Fit_to_Screen_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        public static string BBox_Sort_Caption {
            get {
                return ResourceManager.GetString("BBox_Sort_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        public static string BBox_Sort_Tooltip {
            get {
                return ResourceManager.GetString("BBox_Sort_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benchmark ähnelt.
        /// </summary>
        public static string Benchmark_Label {
            get {
                return ResourceManager.GetString("Benchmark_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should the execution engine benchmark the executed functions per second? ähnelt.
        /// </summary>
        public static string Benchmark_Tooltip {
            get {
                return ResourceManager.GetString("Benchmark_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This component has no parameters ähnelt.
        /// </summary>
        public static string BinSettingsVisual_BinSettingsVisual_No_Settings_available_ {
            get {
                return ResourceManager.GetString("BinSettingsVisual_BinSettingsVisual_No_Settings_available_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bold ähnelt.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bring to front ähnelt.
        /// </summary>
        public static string Bring_to_FrontTooltip {
            get {
                return ResourceManager.GetString("Bring_to_FrontTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bullets ähnelt.
        /// </summary>
        public static string Bullets {
            get {
                return ResourceManager.GetString("Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class not found ähnelt.
        /// </summary>
        public static string Class_Not_Found {
            get {
                return ResourceManager.GetString("Class_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classic: ähnelt.
        /// </summary>
        public static string Classic_Label {
            get {
                return ResourceManager.GetString("Classic_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close component ähnelt.
        /// </summary>
        public static string CloseComponentTooltip {
            get {
                return ResourceManager.GetString("CloseComponentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors ähnelt.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align bottom ähnelt.
        /// </summary>
        public static string CompLayout_AlignBottom {
            get {
                return ResourceManager.GetString("CompLayout_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align left ähnelt.
        /// </summary>
        public static string CompLayout_AlignLeft {
            get {
                return ResourceManager.GetString("CompLayout_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align right ähnelt.
        /// </summary>
        public static string CompLayout_AlignRight {
            get {
                return ResourceManager.GetString("CompLayout_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align top ähnelt.
        /// </summary>
        public static string CompLayout_AlignTop {
            get {
                return ResourceManager.GetString("CompLayout_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Biggest height ähnelt.
        /// </summary>
        public static string CompLayout_BiggestHeight {
            get {
                return ResourceManager.GetString("CompLayout_BiggestHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Biggest width ähnelt.
        /// </summary>
        public static string CompLayout_BiggestWidth {
            get {
                return ResourceManager.GetString("CompLayout_BiggestWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move down ähnelt.
        /// </summary>
        public static string CompLayout_MoveDown {
            get {
                return ResourceManager.GetString("CompLayout_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move left ähnelt.
        /// </summary>
        public static string CompLayout_MoveLeft {
            get {
                return ResourceManager.GetString("CompLayout_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move right ähnelt.
        /// </summary>
        public static string CompLayout_MoveRight {
            get {
                return ResourceManager.GetString("CompLayout_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move up ähnelt.
        /// </summary>
        public static string CompLayout_MoveUp {
            get {
                return ResourceManager.GetString("CompLayout_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smallest height ähnelt.
        /// </summary>
        public static string CompLayout_SmallestHeight {
            get {
                return ResourceManager.GetString("CompLayout_SmallestHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smallest width ähnelt.
        /// </summary>
        public static string CompLayout_SmallestWidth {
            get {
                return ResourceManager.GetString("CompLayout_SmallestWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spread horizontal ähnelt.
        /// </summary>
        public static string CompLayout_SpreadHorizontal {
            get {
                return ResourceManager.GetString("CompLayout_SpreadHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spread vertical ähnelt.
        /// </summary>
        public static string CompLayout_SpreadVertical {
            get {
                return ResourceManager.GetString("CompLayout_SpreadVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Component overview ähnelt.
        /// </summary>
        public static string Component_Overview {
            get {
                return ResourceManager.GetString("Component_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard appearance of components ähnelt.
        /// </summary>
        public static string ComponentAppearanceBehaviourGroupHeader {
            get {
                return ResourceManager.GetString("ComponentAppearanceBehaviourGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose how a newly placed component visualization should appear ähnelt.
        /// </summary>
        public static string ComponentAppearanceBehaviourGroupTooltip {
            get {
                return ResourceManager.GetString("ComponentAppearanceBehaviourGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Component connection suggestion delay: ähnelt.
        /// </summary>
        public static string ComponentConnection_Delay {
            get {
                return ResourceManager.GetString("ComponentConnection_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time to keep the mouse pointer in the same position before a popup with a component suggestion appears ähnelt.
        /// </summary>
        public static string ComponentConnection_Delay_Tooltip {
            get {
                return ResourceManager.GetString("ComponentConnection_Delay_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conversion to different data type, ambiguity may occur ähnelt.
        /// </summary>
        public static string ConversionAmbig {
            get {
                return ResourceManager.GetString("ConversionAmbig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid connection. ähnelt.
        /// </summary>
        public static string ConversionNone {
            get {
                return ResourceManager.GetString("ConversionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK! ähnelt.
        /// </summary>
        public static string ConversionOK {
            get {
                return ResourceManager.GetString("ConversionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data types match. ähnelt.
        /// </summary>
        public static string ConversionSame {
            get {
                return ResourceManager.GetString("ConversionSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t connect to itself. ähnelt.
        /// </summary>
        public static string ConversionSelf {
            get {
                return ResourceManager.GetString("ConversionSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STOP! ähnelt.
        /// </summary>
        public static string ConversionStop {
            get {
                return ResourceManager.GetString("ConversionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING! ähnelt.
        /// </summary>
        public static string ConversionWarning {
            get {
                return ResourceManager.GetString("ConversionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string DataTooltip {
            get {
                return ResourceManager.GetString("DataTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data type colors: ähnelt.
        /// </summary>
        public static string Datatypecolors_Label {
            get {
                return ResourceManager.GetString("Datatypecolors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug ähnelt.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show debugs ähnelt.
        /// </summary>
        public static string DebugCheckedFalseTooltip {
            get {
                return ResourceManager.GetString("DebugCheckedFalseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide debugs ähnelt.
        /// </summary>
        public static string DebugCheckedTrueTooltip {
            get {
                return ResourceManager.GetString("DebugCheckedTrueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease indent ähnelt.
        /// </summary>
        public static string Decrease_Indent {
            get {
                return ResourceManager.GetString("Decrease_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance predetermined by the component ähnelt.
        /// </summary>
        public static string DefaultComponentAppearance {
            get {
                return ResourceManager.GetString("DefaultComponentAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all messages ähnelt.
        /// </summary>
        public static string Delete_all_messages {
            get {
                return ResourceManager.GetString("Delete_all_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear log panel ähnelt.
        /// </summary>
        public static string Delete_all_messagesTooltip {
            get {
                return ResourceManager.GetString("Delete_all_messagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag ähnelt.
        /// </summary>
        public static string Drag {
            get {
                return ResourceManager.GetString("Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some editing functions are disabled during execution ähnelt.
        /// </summary>
        public static string EditingDisabled {
            get {
                return ResourceManager.GetString("EditingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elevate ähnelt.
        /// </summary>
        public static string ElevateTooltip {
            get {
                return ResourceManager.GetString("ElevateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter name ähnelt.
        /// </summary>
        public static string Enter_Name {
            get {
                return ResourceManager.GetString("Enter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show error ähnelt.
        /// </summary>
        public static string ErrorCheckedFalseTooltip {
            get {
                return ResourceManager.GetString("ErrorCheckedFalseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide error ähnelt.
        /// </summary>
        public static string ErrorCheckedTrueTooltip {
            get {
                return ResourceManager.GetString("ErrorCheckedTrueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing... ähnelt.
        /// </summary>
        public static string Executing___ {
            get {
                return ResourceManager.GetString("Executing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default workspace font used by TextInput and TextOutput components ähnelt.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes the standard font (type, size) that is used for TextInput and TextOutput components ähnelt.
        /// </summary>
        public static string FontTooltip {
            get {
                return ResourceManager.GetString("FontTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function colors: ähnelt.
        /// </summary>
        public static string Functioncolors_Label {
            get {
                return ResourceManager.GetString("Functioncolors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General workspace settings ähnelt.
        /// </summary>
        public static string GeneralWorkspaceSettings {
            get {
                return ResourceManager.GetString("GeneralWorkspaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global progress bar ähnelt.
        /// </summary>
        public static string Global_Progressbar {
            get {
                return ResourceManager.GetString("Global_Progressbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation finished after {0} (To stop the workspace please push the stop button or enter new data to start a new calculation) ähnelt.
        /// </summary>
        public static string GlobalProgressBar_Description {
            get {
                return ResourceManager.GetString("GlobalProgressBar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables/disables the global progress bar shown on top of the WorkspaceManager ähnelt.
        /// </summary>
        public static string GlobalProgressBarTooltip {
            get {
                return ResourceManager.GetString("GlobalProgressBarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grow font ähnelt.
        /// </summary>
        public static string Grow_Font {
            get {
                return ResourceManager.GetString("Grow_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GUI update interval: ähnelt.
        /// </summary>
        public static string GUIUpdateinterval_Label {
            get {
                return ResourceManager.GetString("GUIUpdateinterval_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets the interval for updating GUI elements during execution ähnelt.
        /// </summary>
        public static string GUIUpdateinterval_Tooltip {
            get {
                return ResourceManager.GetString("GUIUpdateinterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hash: ähnelt.
        /// </summary>
        public static string Hash_Label {
            get {
                return ResourceManager.GetString("Hash_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string HelpTooltip {
            get {
                return ResourceManager.GetString("HelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase indent ähnelt.
        /// </summary>
        public static string Increase_Indent {
            get {
                return ResourceManager.GetString("Increase_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show information ähnelt.
        /// </summary>
        public static string InfoCheckedFalseTooltip {
            get {
                return ResourceManager.GetString("InfoCheckedFalseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide information ähnelt.
        /// </summary>
        public static string InfoCheckedTrueTooltip {
            get {
                return ResourceManager.GetString("InfoCheckedTrueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italic ähnelt.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        public static string Loading_ {
            get {
                return ResourceManager.GetString("Loading_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock ähnelt.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log ähnelt.
        /// </summary>
        public static string LogTooltip {
            get {
                return ResourceManager.GetString("LogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximize ähnelt.
        /// </summary>
        public static string MaximizeTooltip {
            get {
                return ResourceManager.GetString("MaximizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize ähnelt.
        /// </summary>
        public static string MinimizeTooltip {
            get {
                return ResourceManager.GetString("MinimizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to back ähnelt.
        /// </summary>
        public static string Move_to_BackTooltip {
            get {
                return ResourceManager.GetString("Move_to_BackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is a new workspace. ähnelt.
        /// </summary>
        public static string NewWorkspaceTooltip {
            get {
                return ResourceManager.GetString("NewWorkspaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No data ähnelt.
        /// </summary>
        public static string No_data {
            get {
                return ResourceManager.GetString("No_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numbering ähnelt.
        /// </summary>
        public static string Numbering {
            get {
                return ResourceManager.GetString("Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open file ähnelt.
        /// </summary>
        public static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace ähnelt.
        /// </summary>
        public static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphical editor for a CT2 workspace ähnelt.
        /// </summary>
        public static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presentation ähnelt.
        /// </summary>
        public static string PresentationTooltip {
            get {
                return ResourceManager.GetString("PresentationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protocols: ähnelt.
        /// </summary>
        public static string Protocols_Label {
            get {
                return ResourceManager.GetString("Protocols_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rearrange all lines ähnelt.
        /// </summary>
        public static string Rearrange_all_lines {
            get {
                return ResourceManager.GetString("Rearrange_all_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reduce ähnelt.
        /// </summary>
        public static string ReduceTooltip {
            get {
                return ResourceManager.GetString("ReduceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat ähnelt.
        /// </summary>
        public static string RepeatTooltip {
            get {
                return ResourceManager.GetString("RepeatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset component connection statistics ähnelt.
        /// </summary>
        public static string ResetCCS {
            get {
                return ResourceManager.GetString("ResetCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset colors ähnelt.
        /// </summary>
        public static string ResetColors_Label {
            get {
                return ResourceManager.GetString("ResetColors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset all colors to their default values. ähnelt.
        /// </summary>
        public static string ResetColors_Tooltip {
            get {
                return ResourceManager.GetString("ResetColors_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save File ähnelt.
        /// </summary>
        public static string Save_File {
            get {
                return ResourceManager.GetString("Save_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die second ähnelt.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show component connection propositions ähnelt.
        /// </summary>
        public static string Show_ComponentConnection_Proposition {
            get {
                return ResourceManager.GetString("Show_ComponentConnection_Proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows the most frequently used components when holding a connection line ähnelt.
        /// </summary>
        public static string Show_ComponentConnection_Proposition_Tooltip {
            get {
                return ResourceManager.GetString("Show_ComponentConnection_Proposition_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Embedded Components ähnelt.
        /// </summary>
        public static string Show_IControlsTooltip {
            get {
                return ResourceManager.GetString("Show_IControlsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shrink font ähnelt.
        /// </summary>
        public static string Shrink_Font {
            get {
                return ResourceManager.GetString("Shrink_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep time: ähnelt.
        /// </summary>
        public static string SleepTime_Label {
            get {
                return ResourceManager.GetString("SleepTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the sleeping-time between execution of functions (in miliseconds) ähnelt.
        /// </summary>
        public static string SleepTime_Tooltip {
            get {
                return ResourceManager.GetString("SleepTime_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steganography: ähnelt.
        /// </summary>
        public static string Steganography_Label {
            get {
                return ResourceManager.GetString("Steganography_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symmetric block: ähnelt.
        /// </summary>
        public static string Symmetricblock_Label {
            get {
                return ResourceManager.GetString("Symmetricblock_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronous events ähnelt.
        /// </summary>
        public static string SynchronousEvents_Label {
            get {
                return ResourceManager.GetString("SynchronousEvents_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the behaviour of event handling of the execution engine ähnelt.
        /// </summary>
        public static string SynchronousEvents_Tooltip {
            get {
                return ResourceManager.GetString("SynchronousEvents_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template placeholder replacement ähnelt.
        /// </summary>
        public static string TemplateReplacement {
            get {
                return ResourceManager.GetString("TemplateReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables/disables the replacement of template placeholders, e.g. $something$, with text of the language currently selected in CrypTool 2 ähnelt.
        /// </summary>
        public static string TemplateReplacementTooltip {
            get {
                return ResourceManager.GetString("TemplateReplacementTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open/close the bar with the settings of the selected components of this workspace (Ctrl + I) ähnelt.
        /// </summary>
        public static string Toggle_Plugin_Parameters {
            get {
                return ResourceManager.GetString("Toggle_Plugin_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools: ähnelt.
        /// </summary>
        public static string Tools_Label {
            get {
                return ResourceManager.GetString("Tools_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Underline ähnelt.
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock ähnelt.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New project ähnelt.
        /// </summary>
        public static string unnamed_project {
            get {
                return ResourceManager.GetString("unnamed_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User interface settings ähnelt.
        /// </summary>
        public static string UserInterfaceSettings {
            get {
                return ResourceManager.GetString("UserInterfaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show warning ähnelt.
        /// </summary>
        public static string WarningCheckedFalseTooltip {
            get {
                return ResourceManager.GetString("WarningCheckedFalseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide warning ähnelt.
        /// </summary>
        public static string WarningCheckedTrueTooltip {
            get {
                return ResourceManager.GetString("WarningCheckedTrueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception during disposing of the model: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Dispose_Exception_during_disposing_of_the_Model___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Dispose_Exception_during_disposing_of_the_Model___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception during stopping of the ExecutionEngine: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Dispose_Exception_during_stopping_of_the_ExecutionEngine___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Dispose_Exception_during_stopping_of_the_ExecutionEngine___" +
                        "0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GuiUpdateInterval cannot be &lt;=0; Use GuiUpdateInterval = 1 ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Execute_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Execute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not set GuiUpdateInterval: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Execute_Could_not_set_GuiUpdateInterval___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Execute_Could_not_set_GuiUpdateInterval___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not set SleepTime: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Execute_Could_not_set_SleepTime___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Execute_Could_not_set_SleepTime___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception during the execution: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Execute_Exception_during_the_execution___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Execute_Exception_during_the_execution___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute model now! ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Execute_Execute_Model_now_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Execute_Execute_Model_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep time cannot be &lt;0; Use sleep time = 0 ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Execute_SleepTime {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Execute_SleepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load model: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Open_Could_not_load_Model___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Open_Could_not_load_Model___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading model: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Open_Loading_Model___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Open_Loading_Model___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception while printing: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Print_Exception_while_printing___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Print_Exception_while_printing___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printed {0} pages of document &apos;{1}&apos; ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Print_Printed__0__pages_of_document___1__ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Print_Printed__0__pages_of_document___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Printing document &apos;{0}&apos; now ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Print_Printing_document___0___now {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Print_Printing_document___0___now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not redo: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Redo_Can_not_redo___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Redo_Can_not_redo___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not save model: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Save_Could_not_save_Model___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Save_Could_not_save_Model___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving model: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Save_Saving_Model___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Save_Saving_Model___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not undo: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_Undo_Can_not_undo___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_Undo_Can_not_undo___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception during the stopping of the execution: {0} ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_waitingStop_Exception_during_the_stopping_of_the_execution___0_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_waitingStop_Exception_during_the_stopping_of_the_execution_" +
                        "__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping execution. ähnelt.
        /// </summary>
        public static string WorkspaceManagerClass_waitingStop_Stopping_execution_ {
            get {
                return ResourceManager.GetString("WorkspaceManagerClass_waitingStop_Stopping_execution_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace ähnelt.
        /// </summary>
        public static string WorkspaceManagerSettings {
            get {
                return ResourceManager.GetString("WorkspaceManagerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace settings ähnelt.
        /// </summary>
        public static string WorkspaceManagerSettingsTitle {
            get {
                return ResourceManager.GetString("WorkspaceManagerSettingsTitle", resourceCulture);
            }
        }
    }
}
